groups:
- name: gluster-volume.rules
  rules:
  - expr: |
      sum(max(gluster_subvol_capacity_used_bytes{job="glusterd2-client"}) BY (volume, subvolume)) BY (volume)
    record: gluster:volume_capacity_used_bytes_total:sum
  - expr: |
      sum(max(gluster_subvol_capacity_total_bytes{job="glusterd2-client"}) BY (volume, subvolume)) BY (volume)
    record: gluster:volume_capacity_total_bytes:sum
