---
# baseURL: "https://monitoring.mixins.dev/"
baseURL: ""
languageCode: "en-us"
title: "Monitoring Mixins"

theme: 'cayman'

# Google analytics
# googleAnalytics: UA-123456789-1

permalinks:
  post: /:filename/

params:
  project_name: Monitoring Mixins

  project_tagline: Combination of alerts, recording rules, and dashboards for prometheus exporters

menu:
  nav:
    - name: Homepage
      url: /
      weight: 1
    - name: About
      url: "https://github.com/monitoring-mixins/docs"
      weight: 2

